get_filename_component(INSTALLED_PREFIX ${Newbase_DIR} DIRECTORY)
get_filename_component(INSTALLED_PREFIX ${INSTALLED_PREFIX} DIRECTORY)
get_filename_component(INSTALLED_PREFIX ${INSTALLED_PREFIX} DIRECTORY)
set(Newbase_INCLUDE_DIRS ${INSTALLED_PREFIX}/include)
set(Newbase_INSTALLED_INCLUDE_DIRS ${INSTALLED_PREFIX}/include/newbase)
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    option(Newbase_USE_STATIC_LIBS "Newbase use static libs" OFF)

    if(Newbase_USE_STATIC_LIBS)
        set(Newbase_LIBRARIES  ${INSTALLED_PREFIX}/lib/libNewbase.a)
    else()
        set(Newbase_LIBRARIES  ${INSTALLED_PREFIX}/lib/libNewbase.so)
    endif()

    if(NOT EXISTS ${Newbase_LIBRARIES})
        message(STATUS "Library ${Newbase_LIBRARIES} not found.")
    endif()
    set(Newbase_INSTALLED_LIBRARIES ${Newbase_LIBRARIES})
else()
    set(Newbase_INSTALLED_LIBRARIES ${INSTALLED_PREFIX}/lib/NewBase.lib)
    set(Newbase_LIBRARIES  ${INSTALLED_PREFIX}/lib/Newbase.lib)
endif()
